void print_alphabet();
void Camb();
int str_len(char* str);
int* ft_rev_int_tab(int* tab, int size);
int* min(int* tab, int size, int j);
int* sort(int* tab, int size);
char* cpstr(char* dis, char* src);
char* cpnstr(char* dis, char* src, int n);
int is_alpha(char* str);
char* to_upper(char* str);
char* capital(char* str);
int strcamp_ft(char* str_01, char* str_02);
char* catstr_ft(char* dis, char* src);
char* strstr_ft(char* str, char* substr);
int ft_recursive_fact(int a);
int ft_power_recursion(int nb, int power);
int ft_fibonacci(int index);
float ft_sqrt_heron(float nb, int index);
float ft_sqrt(float x);
int next_prime(int nb);
char* ft_strdup(char* src);
int* ft_range(int min, int max);
char* ft_strjoin(int size, char** strs, char* sep);
char** ft_split(char* str, char* charset);
void  ft_foreach(int* tab, int size, void(*f)(int));
int* ft_map(int* tab, int size, int(*f)(int));
int ft_is_sort(int* tab, int size, int(*f)(int, int));
int compare(int a, int b);